server {
    listen 80;
    server_name _;

    client_max_body_size 2m;

    location = / {
        proxy_pass http://flask:5000;
    }

    location /static/ {
        proxy_pass http://flask:5000;
    }

    location /A/lab3-ssti-pebble {
        proxy_pass http://pebble:7000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /B/lab3-ssti-pebble {
        proxy_pass http://pebble:7000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /A/lab5-xxe {
        proxy_pass http://php:80;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /B/lab5-xxe {
        proxy_pass http://php:80;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /zorum {
        proxy_pass http://php:80;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        proxy_pass http://flask:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
