server {
    listen 80;
    server_name portal-clientes.lab.local;
    location / {
        proxy_pass http://sqli-app:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name intranet.lab.local;
    location / {
        proxy_pass http://idor-app:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name gestion.lab.local;
    location / {
        proxy_pass http://weakcreds-app:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name catalogo.lab.local;
    location / {
        proxy_pass http://catalogo-app:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name soporte.lab.local;
    location / {
        proxy_pass http://xss-app:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name backup-docs.lab.local;
    location / {
        proxy_pass http://cmdinj-app:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name reportes-xml.lab.local;
    location / {
        proxy_pass http://xxe-app:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80 default_server;
    server_name _;
    return 404;
}
